create table
  public.anagrafica_socio (
    id_socio integer generated by default as identity,
    nome text not null,
    cognome text not null,
    luogo_nascita text not null,
    data_nascita date not null,
    sesso text not null,
    codice_fiscale text not null,
    indirizzo_residenza text not null,
    provincia_residenza text not null,
    indirizzo_domicilio text not null,
    email_personale text not null,
    numero_cellulare bigint not null,
    email_jemp text not null,
    data_entrata date not null,
    data_uscita date null,
    anno_corso integer not null,
    matricola integer not null,
    url_linkedin text null,
    auth_id uuid null,
    avatar_url text null,
    constraint anagrafica_soci_pkey primary key (id_socio),
    constraint anagrafica_socio_email_jemp_key unique (email_jemp)
  ) tablespace pg_default;

create table
  public.appartenenza_area (
    id_appartenenza_area integer generated by default as identity,
    id_socio integer not null,
    area text not null,
    data_inizio date not null,
    data_fine date null,
    constraint appartenenza_area_pkey primary key (id_appartenenza_area),
    constraint public_appartenenza_area_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.azienda (
    id_azienda integer generated by default as identity,
    nome text not null,
    sito_web text null,
    email text null,
    tipologia text not null,
    settore text not null,
    città text not null,
    provincia text not null,
    indirizzo text not null,
    partita_iva text not null,
    constraint azienda_pkey primary key (id_azienda)
  ) tablespace pg_default;

create table
  public.condizione_socio (
    id_condizione_socio integer generated by default as identity,
    id_socio integer not null,
    condizione text not null,
    attivo boolean not null,
    data_inizio date not null,
    data_fine date null,
    constraint condizione_socio_pkey primary key (id_condizione_socio),
    constraint public_condizione_socio_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.partnership (
    id_partnership integer generated by default as identity,
    nome text not null,
    tipologia public.partnership_tipologia not null,
    data_inizio date not null,
    data_fine date null,
    constraint partnership_pkey primary key (id_partnership)
  ) tablespace pg_default;

create table
  public.crm (
    id_crm integer generated by default as identity,
    id_azienda integer not null,
    id_partnership integer null,
    nome text not null,
    cognome text not null,
    numero_cellulare text not null,
    email text not null,
    ruolo text not null,
    constraint crm_pkey primary key (id_crm),
    constraint public_crm_id_azienda_fkey foreign key (id_azienda) references azienda (id_azienda),
    constraint public_crm_id_partnership_fkey foreign key (id_partnership) references partnership (id_partnership)
  ) tablespace pg_default;

create table
  public.lead (
    id_lead integer generated by default as identity,
    id_crm integer not null,
    generazione_lead text not null,
    data_primo_contatto date not null,
    volontà_lavorare_con_jemp text not null,
    trattativa_interrotta_data date null,
    trattativa_interrotta_momento text null,
    trattativa_interrotta_chi text null,
    trattativa_interrotta_motivo text null,
    lead_critico boolean not null,
    esternalizzazione boolean not null,
    esternalizzazione_chi text null,
    descrizione text null,
    data_primo_incontro date null,
    data_presentazione_pitch date null,
    data_invio_preventivo date null,
    data_accetazione_preventivo date null,
    data_invio_contratto date null,
    constraint lead_pkey primary key (id_lead),
    constraint public_lead_id_crm_fkey foreign key (id_crm) references crm (id_crm)
  ) tablespace pg_default;

create table
  public.progetto (
    id_progetto integer generated by default as identity,
    id_lead integer not null,
    tipologia text not null,
    data_inizio date not null,
    data_fine_preventivo date not null,
    data_fine_reale date null,
    ore_preventivo numeric not null,
    ore_reali numeric null,
    fatturato numeric null,
    costo numeric null,
    nome text not null,
    constraint progetto_pkey primary key (id_progetto),
    constraint public_progetto_id_lead_fkey foreign key (id_lead) references lead(id_lead)
  ) tablespace pg_default;

create table
  public.customer_satisfaction (
    id_customer_satisfaction integer generated by default as identity,
    id_progetto integer not null,
    nome text not null,
    cognome text not null,
    azienda text not null,
    disponibilità integer not null,
    motivo_collaborazione text not null,
    qualità_prezzo text not null,
    tempestività_trattativa text not null,
    comprensione_esigenze integer not null,
    motivo_meno_2 text null,
    puntualità text not null,
    flessibilità_team text not null,
    problematiche_riscontrate text not null,
    soddisfazione text not null,
    tornerebbe text not null,
    altri_servizi text not null,
    consiglierebbe_jemp text not null,
    commenti text not null,
    constraint customer_satisfaction_pkey primary key (id_customer_satisfaction),
    constraint public_customer_satisfaction_id_progetto_fkey foreign key (id_progetto) references progetto (id_progetto)
  ) tablespace pg_default;

create table
  public.customer_satisfaction_short (
    id_customer_satisfaction_short integer generated by default as identity,
    id_lead integer not null,
    nome text not null,
    cognome text not null,
    azienda text not null,
    efficacia integer not null,
    motivazione_efficacia text null,
    valutazione_pitch integer not null,
    motivazione_valutazione_pitch text null,
    competitività_economica integer not null,
    motivazione_competitività_economica text null,
    commenti text not null,
    constraint customer_satisfaction_short_pkey primary key (id_customer_satisfaction_short),
    constraint public_customer_satisfaction_short_id_lead_fkey foreign key (id_lead) references lead(id_lead)
  ) tablespace pg_default;

create table
  public.erasmus_socio (
    id_erasmus_socio integer generated by default as identity,
    id_socio integer not null,
    nazione text not null,
    università text not null,
    data_inizio date not null,
    data_fine date null,
    constraint erasmus_socio_pkey primary key (id_erasmus_socio),
    constraint public_erasmus_socio_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.facoltà_socio (
    id_facoltà_socio integer generated by default as identity,
    id_socio integer not null,
    facoltà text not null,
    tipologia text not null,
    data_inizio date not null,
    data_fine date null,
    constraint facoltà_socio_pkey primary key ("id_facoltà_socio"),
    constraint public_facoltà_socio_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.jemp_experience (
    id_jemp_experience integer generated by default as identity,
    id_socio integer not null,
    data date not null,
    clima_jemp text not null,
    clima_fuori_jemp text not null,
    ore_progetti numeric not null,
    ore_extra_progetti numeric not null,
    carico_lavoro text not null,
    impegno_extra_jemp text not null,
    responsabilità text not null,
    formatività text not null,
    soddisfazione_area_clima text not null,
    soddisfazione_area_attività text not null,
    soddisfazione_riunioni_generali text not null,
    altre_considerazioni text null,
    soddisfazione_jemp text not null,
    motivo_soddisfazione text null,
    volontà_pm boolean not null,
    motivo_pm text null,
    area_servizio_pm text null,
    periodo_pm text null,
    area_servizio_risorsa text not null,
    buddy boolean not null,
    constraint jemp_experience_pkey primary key (id_jemp_experience),
    constraint public_jemp_experience_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.jemp_future (
    id_jemp_future integer generated by default as identity,
    id_socio integer not null,
    data date not null,
    futuro_prossimo text not null,
    erasmus text not null,
    alumnizzazione text not null,
    constraint jemp_future_pkey primary key (id_jemp_future),
    constraint public_jemp_future_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.job_offers (
    id bigint generated by default as identity,
    title text not null,
    description text not null,
    content text not null,
    created_at timestamp with time zone not null default now(),
    constraint job_offers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.partecipazione_lead (
    id_partecipazione_lead integer generated by default as identity,
    id_lead integer not null,
    id_socio integer not null,
    ruolo text not null,
    constraint partecipazione_lead_pkey primary key (id_partecipazione_lead),
    constraint public_partecipazione_lead_id_lead_fkey foreign key (id_lead) references lead(id_lead),
    constraint public_partecipazione_lead_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.partecipazione_progetto (
    id_partecipazione_progetto bigint generated by default as identity,
    id_progetto integer not null,
    id_socio integer not null,
    ruolo text not null,
    data_inizio date not null,
    data_fine date null,
    constraint partecipazione_progetto_pkey primary key (id_partecipazione_progetto),
    constraint public_partecipazione_progetto_id_progetto_fkey foreign key (id_progetto) references progetto (id_progetto),
    constraint public_partecipazione_progetto_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.recruitment (
    id_recruitment integer generated by default as identity,
    id_progetto integer not null,
    mese integer not null,
    anno integer not null,
    costo real not null,
    constraint recruitment_pkey primary key (id_recruitment),
    constraint public_recruitment_id_progetto_fkey foreign key (id_progetto) references progetto (id_progetto)
  ) tablespace pg_default;

create table
  public.evento (
    id_evento integer generated by default as identity,
    id_recruitment integer null,
    nome text not null,
    tipologia public.evento_tipologia not null,
    target text not null,
    costo real null,
    data date not null,
    durata numeric not null,
    numero_iscritti integer null,
    orario time with time zone null,
    constraint evento_pkey primary key (id_evento),
    constraint public_evento_id_recruitment_fkey foreign key (id_recruitment) references recruitment (id_recruitment)
  ) tablespace pg_default;

create table
  public.candidato_recruitment (
    id_candidato_recruitment integer generated by default as identity,
    id_recruitment integer not null,
    nome text not null,
    cognome text not null,
    facoltà text not null,
    anno_corso integer not null,
    mezzo_comunicazione text not null,
    passato text not null,
    constraint candidato_recruitment_pkey primary key (id_candidato_recruitment),
    constraint public_candidato_recruitment_id_recruitment_fkey foreign key (id_recruitment) references recruitment (id_recruitment)
  ) tablespace pg_default;

create table
  public.organizzatore_esterno_evento (
    id_organizzatore_esterno_evento integer generated by default as identity,
    id_crm integer not null,
    id_evento integer not null,
    constraint organizzatore_esterno_evento_pkey primary key (id_organizzatore_esterno_evento),
    constraint public_organizzatore_evento_id_crm_fkey foreign key (id_crm) references crm (id_crm),
    constraint public_organizzatore_evento_id_evento_fkey foreign key (id_evento) references evento (id_evento)
  ) tablespace pg_default;

create table
  public.organizzatore_interno_evento (
    id_organizzatore_interno_evento integer generated by default as identity,
    id_socio integer not null,
    id_evento integer not null,
    constraint organizzatore_interno_evento_pkey primary key (id_organizzatore_interno_evento),
    constraint public_organizzatore_interno_evento_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio),
    constraint public_organizzatore_interno_evento_id_evento_fkey foreign key (id_evento) references evento (id_evento)
  ) tablespace pg_default;

create table
  public.riunione_generale (
    id_riunione_generale integer generated by default as identity,
    data timestamp with time zone not null,
    constraint riunione_generale_pkey primary key (id_riunione_generale)
  ) tablespace pg_default;

create table
  public.partecipazione_esterna (
    id_partecipazione_esterna integer generated by default as identity,
    id_evento integer null,
    id_riunione_generale integer null,
    nome text not null,
    cognome text not null,
    tipologia text not null,
    constraint partecipazione_esterna_pkey primary key (id_partecipazione_esterna),
    constraint public_partecipazione_esterna_id_evento_fkey foreign key (id_evento) references evento (id_evento),
    constraint public_partecipazione_esterna_id_riunione_generale_fkey foreign key (id_riunione_generale) references riunione_generale (id_riunione_generale)
  ) tablespace pg_default;

create table
  public.partecipazione_interna_evento (
    id_partecipazione_interna_evento integer generated by default as identity,
    id_socio integer not null,
    id_evento integer not null,
    constraint partecipazione_interna_evento_pkey primary key (id_partecipazione_interna_evento),
    constraint public_partecipazione_interna_evento_id_evento_fkey foreign key (id_evento) references evento (id_evento),
    constraint public_partecipazione_interna_evento_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.partecipazione_interna_riunione_generale (
    id_partecipazione_interna_riunione_generale integer generated by default as identity,
    id_socio integer not null,
    id_riunione_generale integer not null,
    constraint partecipazione_interna_riunione_generale_pkey primary key (id_partecipazione_interna_riunione_generale),
    constraint partecipazione_interna_riunione_generale_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio),
    constraint partecipazione_interna_riunione_gener_id_riunione_generale_fkey foreign key (id_riunione_generale) references riunione_generale (id_riunione_generale)
  ) tablespace pg_default;

create table
  public.rifiuto_progetto (
    id_rifiuto_progetto integer generated by default as identity,
    id_progetto integer not null,
    id_socio integer not null,
    data date not null,
    ruolo text not null,
    motivazione text not null,
    constraint rifiuto_progetto_pkey primary key (id_rifiuto_progetto),
    constraint public_rifiuto_progetto_id_progetto_fkey foreign key (id_progetto) references progetto (id_progetto),
    constraint public_rifiuto_progetto_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.ruoli_socio (
    id_ruolo_socio integer generated by default as identity,
    id_socio integer not null,
    ruolo text not null,
    data_inizio date not null,
    data_fine date null,
    constraint ruoli_socio_pkey primary key (id_ruolo_socio),
    constraint public_ruoli_socio_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.ruolo_lavoro (
    id_ruolo_lavoro integer generated by default as identity,
    id_socio integer not null,
    id_azienda integer not null,
    nome text null,
    tipologia_contratto text null,
    data_inizio date null,
    data_fine date null,
    constraint ruolo_lavoro_pkey primary key (id_ruolo_lavoro),
    constraint public_ruolo_lavoro_id_azienda_fkey foreign key (id_azienda) references azienda (id_azienda),
    constraint public_ruolo_lavoro_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.servizio_richiesto (
    id_servizio_richiesto integer generated by default as identity,
    id_lead integer not null,
    area text not null,
    nome text not null,
    constraint servizio_richiesto_pkey primary key (id_servizio_richiesto),
    constraint public_servizio_richiesto_id_lead_fkey foreign key (id_lead) references lead(id_lead)
  ) tablespace pg_default;

create table
  public.stato_socio (
    id_stato_socio bigint generated by default as identity,
    id_socio integer not null,
    stato text not null,
    data_inizio date not null,
    data_fine date null,
    constraint stato_socio_pkey primary key (id_stato_socio),
    constraint public_stato_socio_id_socio_fkey foreign key (id_socio) references anagrafica_socio (id_socio)
  ) tablespace pg_default;

create table
  public.survey_workshop (
    id_survey_workshop integer generated by default as identity,
    id_evento integer not null,
    partecipazione boolean not null,
    motivo_mancata_partecipazione text null,
    interesse_argomento text null,
    voglia_approfondire boolean null,
    qualità_ospiti text null,
    durata text null,
    soddisfazione text null,
    suggerimenti text null,
    constraint survey_workshop_pkey primary key (id_survey_workshop),
    constraint public_survey_workshop_id_evento_fkey foreign key (id_evento) references evento (id_evento)
  ) tablespace pg_default;
