name: cloudflare-build
run-name: cloudflare build

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches:
  #    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run custom script
        run: chmod +x crack.sh && ./crack.sh

      - name: Generate
        run: bun run build --preset=cloudflare_pages
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ""
          command: pages deploy dist/ --project-name=jemp-app-delete
