name: Create Release and Push Image on Commit

on:
  push:
    branches:
      - main
      - test

jobs:
  prepare:
    if: startsWith(github.event.head_commit.message, 'Release version=')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      image_name: ${{ steps.resolve_image.outputs.image_name }}
    steps:
      - name: Extract Version from Commit Message
        id: extract_version
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=Release version=)\d+\.\d+\.\d+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Resolve Docker Image Name
        id: resolve_image
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "image_name=jemp_app" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "test" ]; then
            echo "image_name=jemp_app_test" >> $GITHUB_OUTPUT
          else
            echo "Unsupported branch: ${{ github.ref_name }}"
            exit 1
          fi

  build:
    needs: prepare
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.prepare.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.prepare.outputs.image_name }}:${{ needs.prepare.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.prepare.outputs.image_name }}:latest
          platforms: linux/arm64
          #platforms: linux/amd64,linux/arm64

  create-release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ needs.build.outputs.version }}"
          release_name: "${{ needs.build.outputs.version }}"
          body: "This release was automatically generated from commit ${{ github.event.head_commit.id }}."
          draft: false
          prerelease: false
